### ISSUE TITLE
update plz 

### ISSUE THREAD

**Issue by KwonIkYoung** [Qrilee/Jrebel_for_Android_Cracked#3]
Thanks to it
hi gradle 3.5 not working 
plz update

**Comment by Qrilee** [comment]
Here's the latest crack method
http://blog.lanyus.com/archives/299.html
1 . Generating a random guid ,in java ,it called uuid
2. click 'Connect to License Server', input ‘http://idea.lanyus.com/’ + uuid ,such as http://idea.lanyus.com/0b2cab97-d78c-431d-939c-61dc85f0906d
int the group url
3. 
Random input  a email url
4. click Activate JRebel for Android
